#!/bin/sh

uci delete network.wan 2>/dev/null
uci delete network.wan6 2>/dev/null

uci set network.wwan='interface'
uci set network.wwan.proto='quectel'
uci set network.wwan.auth='none'
uci set network.wwan.delay='5'
uci set network.wwan.mtu='1500'
uci set network.wwan.pdptype='ipv4v6'
uci set network.wwan.device='/dev/cdc-wdm0'
uci set network.wwan.apn='internet'
uci add_list network.wwan.dns='1.1.1.1'
uci add_list network.wwan.dns='1.0.0.1'

uci commit network

exit 0
