#!/bin/sh

wget -O /tmp/xray.gz https://github.com/pru79/pruhaha/raw/refs/heads/main/xray25.3.31.gz
gunzip /tmp/xray.gz
chmod +x /tmp/xray
cp /tmp/xray /usr/bin/xray
rm -f /tmp/xray
uci set passwall2.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall2
/etc/init.d/passwall2 restart

if ! grep -q "/etc/init.d/passwall2 restart" /etc/rc.local; then
    sed -i '/^exit 0/i sleep 25\n/etc/init.d/passwall2 restart' /etc/rc.local
fi

exit 0
