name: Archive and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main-nss

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set variables with date and time
        id: vars
        run: |
          TAG_NAME=backup-$(date +%Y-%m-%d-%H-%M)
          ARCHIVE_NAME=archive-${TAG_NAME}.tar.gz
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Create backup archive
        run: |
          mkdir -p backup
          tar -czvf backup/${{ steps.vars.outputs.archive_name }} $(find . -maxdepth 1 \( -type f -o -name 'bin' -o -name 'feeds' \))

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          name: "Backup ${{ steps.vars.outputs.tag_name }}"
          body: "Automated backup created on ${{ steps.vars.outputs.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload archive to release
        uses: softprops/action-gh-release@v2
        with:
          files: backup/${{ steps.vars.outputs.archive_name }}
          tag_name: ${{ steps.vars.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
